name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout do código
        uses: actions/checkout@v3

      - name: 🧰 Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23' 

      - name: 📦 Instalar dependências
        run: go mod tidy

      - name: 🧪 Rodar testes com cobertura
        run: |
          make test
          make coverage

      - name: 🏗️ Build da aplicação
        run: |
          make build || go build -o bin/app main.go
