name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout do código
        uses: actions/checkout@v3

      - name: 🧰 Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21' # ou 1.23, quando estiver disponível no setup-go

      - name: 📦 Instalar dependências
        run: go mod tidy

      - name: 🧪 Rodar testes com cobertura
        run: |
          make test
          make coverage

      - name: 🏗️ Build da aplicação
        run: |
          make build || go build -o bin/app main.go
